from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewTaskSettings(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_theme = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_theme.setFont(font)
        self.label_theme.setObjectName("label_theme")
        self.verticalLayout_2.addWidget(self.label_theme)
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_2.addWidget(self.label_name)
        self.label_complexity = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_complexity.setFont(font)
        self.label_complexity.setObjectName("label_complexity")
        self.verticalLayout_2.addWidget(self.label_complexity)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_theme = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_theme.setFont(font)
        self.lineEdit_theme.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_theme.setObjectName("lineEdit_theme")
        self.verticalLayout.addWidget(self.lineEdit_theme)
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.comboBox_complexity = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_complexity.setFont(font)
        self.comboBox_complexity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_complexity.setObjectName("comboBox_complexity")
        self.comboBox_complexity.addItem("")
        self.comboBox_complexity.addItem("")
        self.comboBox_complexity.addItem("")
        self.comboBox_complexity.addItem("")
        self.verticalLayout.addWidget(self.comboBox_complexity)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout.addWidget(self.pushButton_back)
        self.pushButton_create = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_create.setFont(font)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout.addWidget(self.pushButton_create)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Параметры новой задачи"))
        self.label_theme.setText(_translate("MainWindow", "Тема задачи"))
        self.label_name.setText(_translate("MainWindow", "Название задачи"))
        self.label_complexity.setText(_translate("MainWindow", "Сложность"))
        self.comboBox_complexity.setItemText(0, _translate("MainWindow", "Легко"))
        self.comboBox_complexity.setItemText(1, _translate("MainWindow", "Средне"))
        self.comboBox_complexity.setItemText(2, _translate("MainWindow", "Сложно"))
        self.comboBox_complexity.setItemText(3, _translate("MainWindow", "Невозможно"))
        self.pushButton_back.setText(_translate("MainWindow", "Назад"))
        self.pushButton_create.setText(_translate("MainWindow", "Созадть"))

